services:
  - type: web
    name: tile-optimization-app
    env: docker
    buildCommand: docker build -t tile-optimization-app .
    startCommand: python run_server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
